name:                dechorder
version:             0.1.0.0
github:              "y-usuzumi/dechorder"
license:             BSD3
author:              "Yukio Usuzumi"
maintainer:          "anohigisavay@gmail.com"
copyright:           "Copyright (c) 2017 Yukio Usuzumi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/y-usuzumi/dechorder#readme>

dependencies:
- array
- array2vector >= 0.1 && < 0.2
- base >= 4.7 && < 5
- BoundedChan
- dsp
- pulse-simple
- vector

default-extensions:
- BangPatterns
- DuplicateRecordFields
- ImplicitParams
- MultiWayIf
- RecordWildCards

library:
  source-dirs: src

executables:
  dechorder:
    main:                Main.hs
    source-dirs:         app/dechorder
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dechorder
  dechorder-sampling-visualizer:
    main:                Main.hs
    source-dirs:         app/dechorder-sampling-visualizer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dechorder
    - gtk >= 0.14
    - Chart
    - Chart-cairo
    - Chart-gtk

tests:
  dechorder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dechorder
    - HUnit-approx
    - pretty
    - tasty
    - tasty-hunit
